POST https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[API_KEY] HTTP/1.1
Content-Type: application/json

{ 
    "email": "joao@teste.com",
    "password": "abc123",
    "returnSecureToken": true
}

###

POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=[API_KEY] HTTP/1.1
Content-Type: application/json

{ 
    "email": "joao@teste.com",
    "password": "abc123",
    "returnSecureToken": true
}

### 

POST https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[API_KEY] HTTP/1.1
Content-Type: application/json

{
    "email": "maria@teste.com",
    "password": "abc123",
    "returnSecureToken": true
}